In [1]:
from fastai.vision.all import *

In [2]:
l = nn.Linear(3, 3)
l.weight.data = torch.Tensor([[0.2, 0.4, -0.5], [-.3, .1, .2], [-.5, .3, .1]])
l.bias.data = torch.Tensor([-0.4, 0.1, .2])

m = nn.Linear(3, 1)
m.weight.data = torch.Tensor([[-0.3, -0.2, .5]])
m.bias.data = torch.Tensor([0.1])

In [3]:
net = nn.Sequential(l, nn.Sigmoid(), m)

In [4]:
l = nn.BCEWithLogitsLoss()
optimizer = SGD(net.parameters(), lr=0.9)

In [5]:
ip = torch.Tensor([1,0,1])
target = torch.Tensor([1])
output = net(ip)

loss = l(output, target)
loss.backward()
optimizer.step()

In [6]:
net[0].weight.data

tensor([[ 0.1719,  0.4000, -0.5281],
        [-0.3211,  0.1000,  0.1789],
        [-0.4478,  0.3000,  0.1522]])

In [8]:
net[0].bias.data

tensor([-0.4281,  0.0789,  0.2522])

In [9]:
net[-1].weight.data

tensor([[-0.1600,  0.0109,  0.6899]])

In [10]:
net[-1].bias.data

tensor([0.5218])

In [17]:
torch.sigmoid(torch.Tensor([-.7,0,-.2]))

tensor([0.3318, 0.5000, 0.4502])

In [22]:
torch.sigmoid(torch.Tensor([.1254]))-1

tensor([-0.4687])

In [47]:
a = -.4;b= .031
a - .9*b

-0.4279

In [28]:
theta = -0.3
delta = -.4687
act = .332
eta = .9
theta -  delta * act * eta

-0.15995243999999997